apiVersion: v1
kind: ServiceAccount
metadata:
 namespace: alchemist
 name: "{{ .Values.knative.task.name }}"
{{- with .Values.deployment.webapp.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
