apiVersion: v1
kind: Service
metadata:
  name: {{ include "alchemist-web-new.fullname" . }}
  labels:
    {{- include "alchemist-web-new.labels" . | nindent 4 }}
  namespace: alchemist
spec:
  type: {{ .Values.deployment.webapp.service.type }}
  ports:
    - port: {{ .Values.deployment.webapp.service.port }}
      targetPort: web-http
      protocol: TCP
      name: svc-http
  selector:
    {{- include "alchemist-web-new.selectorLabels" . | nindent 4 }}
