{{- if .Values.deployment.webapp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: alchemist
  name: {{ include "alchemist-web-new.serviceAccountName" . }}
  labels:
    {{- include "alchemist-web-new.labels" . | nindent 4 }}
  {{- with .Values.deployment.webapp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
