apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: price-viewer
  labels:
    ingestion: price-viewer
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: shellai-secret
          containers:
          - name: price-viewer
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - price_viewer
            envFrom:
              - secretRef:
                  name: alchemist-web
              - configMapRef:
                  name: alchemist-web
              - configMapRef:
                  name: alchemist-jobs
              resources:
                limits:
                  cpu: 4
                  memory: 2Gi
                requests:
                  cpu: 4
                  memory: "2Gi
          restartPolicy: Never

