#This yaml helps to read price viewer data (runs 3AM everyday) using the price viewer dev cluster secrets and
#writes the data to MAHS PROD DL and DB

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: price-viewer
  labels:
    ingestion: price-viewer
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: shellai-secret
          containers:
          - name: price-viewer
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - price-viewer
            env:
              - name: SQLALCHEMY_URL
                valueFrom:
                  secretKeyRef:
                    name: alchemist-web
                    key: SQLALCHEMY_URL_JENKINS_DEV
              - name: ENVIRONMENT
                value: "DEV"
              - name: DATALAKE_NAME
                value: "alchemistadlsdev"
              - name: AZURE_TENANT_ID
                valueFrom:
                  secretKeyRef:
                    name: alchemist-web
                    key: azure_tenant_id_mahs
              - name: AZURE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: alchemist-web
                    key: azure_client_secret_mahs
              - name: AZURE_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: alchemist-web
                    key: AZURE_CLIENT_ID_MAHS
              - name: DEV_CLUSTER_PRICEVIEWER_USER
                valueFrom:
                  secretKeyRef:
                    name: alchemist-web
                    key: DEV_CLUSTER_PRICEVIEWER_USER
              - name: DEV_CLUSTER_PRICEVIEWER_PWD
                valueFrom:
                 secretKeyRef:
                   name: alchemist-web
                   key: DEV_CLUSTER_PRICEVIEWER_PWD
            resources:
              limits:
                cpu: 4
                memory: 2Gi
              requests:
                cpu: 4
                memory: 2Gi
          restartPolicy: Never


