#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: price-viewer
#spec:
#  schedule: "0 3 * * *"
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          containers:
#          - name: price-viewer
#            image: "shellai.azurecr.io/alchemist/alchemist-price-viewer-ingestion:{{ .Values.image.tag }}"
#            args:
#          restartPolicy: OnFailure


apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure