# #This yaml helps to read ccf data (runs 3AM everyday) by scraping the ccf website and
# #writes the data to MAHS PROD DL and DB

# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: ccf
#   labels:
#     ingestion: ccf
# spec:
#   schedule: "0 3 * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           imagePullSecrets:
#           - name: shellai-secret
#           containers:
#           - name: ccf
#             image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#             imagePullPolicy: {{ .Values.image.pullPolicy }}
#             args:
#               - ccf
#             env:
#               - name: SQLALCHEMY_URL
#                 valueFrom:
#                   secretKeyRef:
#                     name: alchemist-web
#                     key: SQLALCHEMY_URL_JENKINS_PROD
#               - name: ENVIRONMENT
#                 value: "PROD"
#               - name: SQLALCHEMY_SSL
#                 value: "TRUE"
#               - name: DATALAKE_NAME
#                 value: "chemsacclerator"
#               - name: AZURE_TENANT_ID
#                 valueFrom:
#                   secretKeyRef:
#                     name: alchemist-web
#                     key: azure_tenant_id_mahs
#               - name: AZURE_CLIENT_SECRET
#                 valueFrom:
#                   secretKeyRef:
#                     name: alchemist-web
#                     key: azure_client_secret_mahs
#               - name: AZURE_CLIENT_ID
#                 valueFrom:
#                   secretKeyRef:
#                     name: alchemist-web
#                     key: AZURE_CLIENT_ID_MAHS
#             resources:
#               limits:
#                 cpu: 2
#                 memory: 2Gi
#               requests:
#                 cpu: 2
#                 memory: 2Gi
#           restartPolicy: Never


