apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alchemist-web.fullname" . }}
  namespace: alchemist
  labels:
    {{- include "alchemist-web.labels" . | nindent 4 }}
    deploymentId: {{ .Values.config.deploymentId | quote }}
    deployemntTimeStamp: {{ .Values.config.deploymentTimestamp | quote }}
spec:
  {{- if not .Values.deployment.webapp.autoscaling.enabled }}
  replicas: {{ .Values.deployment.webapp.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "alchemist-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.deployment.webapp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alchemist-web.selectorLabels" . | nindent 8 }}
        deploymentId: {{ .Values.config.deploymentId | quote }}
        deployemntTimeStamp: {{ .Values.config.deploymentTimestamp | quote }}
      name: {{ include "alchemist-web.fullname" . }}
    spec:
#      serviceAccountName: {{ include "alchemist-web.serviceAccountName" . }}
      serviceAccountName: alchemist-jenkins-acc
      securityContext:
        {{- toYaml .Values.deployment.webapp.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.webapp.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - webapp
          envFrom:
            - secretRef:
                name: alchemist-web
            - configMapRef:
                name: alchemist-web
            - configMapRef:
                name: alchemist-jobs
          ports:
            - name: web-http
              containerPort: {{ .Values.deployment.webapp.containerPort }}
              protocol: TCP
          #          livenessProbe:
          #            httpGet:
          #              path: /health
          #              port: http
          #            initialDelaySeconds: 5
          #            periodSeconds: 5
          #            failureThreshold: 20
          #            timeoutSeconds: 5
          #          readinessProbe:
          #            httpGet:
          #              path: /health
          #              port: http
          #            initialDelaySeconds: 5
          #            periodSeconds: 5
          #            failureThreshold: 20
          #            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.deployment.webapp.resources | nindent 12 }}
        - name: alchemist-huey
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - huey
          ports:
            - name: huey-http
              containerPort: {{ .Values.deployment.huey.containerPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: alchemist-web
            - configMapRef:
                name: alchemist-web
            - configMapRef:
                    name: alchemist-jobs
          #          livenessProbe:
          #            httpGet:
          #              path: /health
          #              port: http
          #            initialDelaySeconds: 5
          #            periodSeconds: 5
          #            failureThreshold: 20
          #            timeoutSeconds: 5
          #          readinessProbe:
          #            httpGet:
          #              path: /health
          #              port: http
          #            initialDelaySeconds: 5
          #            periodSeconds: 5
          #            failureThreshold: 20
          #            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.deployment.webapp.resources | nindent 12 }}
      {{- with .Values.deployment.webapp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.webapp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.webapp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
